// Generated by Bisonc++ V5.02.00 on Thu, 12 Oct 2017 21:59:17 +0530

#ifndef ParserBase_h_included
#define ParserBase_h_included

#include <exception>
#include <vector>
#include <iostream>

namespace // anonymous
{
    struct PI__;
}



class ParserBase
{
    public:
        enum DebugMode__
        {
            OFF           = 0,
            ON            = 1 << 0,
            ACTIONCASES   = 1 << 1
        };

// $insert tokens

    // Symbolic tokens:
    enum Tokens__
    {
        INTEGER_NUMBER = 257,
        NAME,
        INTEGER,
        FIELD,
        PROTOCOL,
        ASSIGN,
        PARTY,
        SEND,
        IDEAL,
        ENV,
        IN,
        OPEN,
        AS,
        RAND,
        USES,
        ABORTING,
        WRAP,
        START,
        BEFORE,
        AFTER,
        EACH,
        SESSION,
        UNKNOWN,
        PORT,
        INPORT,
        OUTPORT,
        FOR,
        OF,
        EXCEPT,
        WHERE,
        IF,
        SET,
        CONNECT,
        TO,
        FORWARD,
        AND,
        ENV_PORT,
        RAND_PORT,
        BOOL,
        PARTIAL,
        WITH,
        DOUBLE_COLON,
        DOUBLE_DOT,
        FROM,
        OR,
        B_AND,
        EQ,
        NE,
        LT,
        LE,
        GE,
        GT,
        UMINUS,
        NOT,
        THEN,
        ELSE,
    };

// $insert STYPE
union STYPE__
{
 
 bool boolean_value;
 int integer_value;
 float float_value;
 std::string * string_value;
 list<Ast *> * ast_list;
 list<string> * n_list;
 Sequence_Ast * sequence_ast;
 Ast * ast;
 connection_param conn;
 pair<Ast*, condition> *conditional;
 Arithmetic_Expr_Ast * arith;
 pair<Data_Type, Ast*> *port_decl;
 pair<Data_Type, string> * type;
 list<pair<Data_Type, string> *> * decl_entry_list;
 pair<string, list<Ast*>*> * p_call;
 pair<bool, Sequence_Ast*> *seq;
 list<pair<Data_Type, Ast*> *>* decl_list;
 pair<bool, Ast*> * opt_each_expr;
 list<pair<pair<Data_Type, string> *, Ast*> *> * port_list;
 pair<pair<Data_Type, string> *, Ast*> * port;
 pair<bool, list<pair<pair<Data_Type, string> *, Ast*> *> *> * opt_port;
};


    private:
        int d_stackIdx__ = -1;
        std::vector<size_t>   d_stateStack__;
        std::vector<STYPE__>  d_valueStack__;

    protected:
        enum Return__
        {
            PARSE_ACCEPT__ = 0,   // values used as parse()'s return values
            PARSE_ABORT__  = 1
        };
        enum ErrorRecovery__
        {
            DEFAULT_RECOVERY_MODE__,
            UNEXPECTED_TOKEN__,
        };
        bool        d_actionCases__ = false;
        bool        d_debug__ = true;
        size_t      d_nErrors__ = 0;
        size_t      d_requiredTokens__;
        size_t      d_acceptedTokens__;
        int         d_token__;
        int         d_nextToken__;
        size_t      d_state__;
        STYPE__    *d_vsp__;
        STYPE__     d_val__;
        STYPE__     d_nextVal__;

        ParserBase();

        void ABORT() const;
        void ACCEPT() const;
        void ERROR() const;
        void clearin();
        bool actionCases() const;
        bool debug() const;
        void pop__(size_t count = 1);
        void push__(size_t nextState);
        void popToken__();
        void pushToken__(int token);
        void reduce__(PI__ const &productionInfo);
        void errorVerbose__();
        size_t top__() const;

    public:
        void setDebug(bool mode);
        void setDebug(DebugMode__ mode);
}; 

inline ParserBase::DebugMode__ operator|(ParserBase::DebugMode__ lhs, 
                                     ParserBase::DebugMode__ rhs)
{
    return static_cast<ParserBase::DebugMode__>(static_cast<int>(lhs) | rhs);
};

inline bool ParserBase::debug() const
{
    return d_debug__;
}

inline bool ParserBase::actionCases() const
{
    return d_actionCases__;
}

inline void ParserBase::ABORT() const
{
    throw PARSE_ABORT__;
}

inline void ParserBase::ACCEPT() const
{
    throw PARSE_ACCEPT__;
}

inline void ParserBase::ERROR() const
{
    throw UNEXPECTED_TOKEN__;
}

inline ParserBase::DebugMode__ operator&(ParserBase::DebugMode__ lhs,
                                     ParserBase::DebugMode__ rhs)
{
    return static_cast<ParserBase::DebugMode__>(
            static_cast<int>(lhs) & rhs);
}

// For convenience, when including ParserBase.h its symbols are available as
// symbols in the class Parser, too.
#define Parser ParserBase


#endif


